### ISSUE TITLE
Change prod flags to use single DEV flag

### ISSUE THREAD

**Issue by NickKania** [birdspotter-project/COS397#55]
We have a couple flags for production, instead, we can use a single flag, either the existing DEBUG or a new DEV flag to reduce the complexity of the .env file. 

NOTE: Change would require updating of the admin manual
https://github.com/birdspotter-project/COS397/blob/c829d1e84da7f0cdc39bbba3d7624cc65eb5ad23/docker-compose/.env.example#L8

**Comment by devinchristianson** [comment]
I like this idea, though I would vote it should be a new DEV flag, as there are good reasons to need to use the DEBUG flag while running the app in production mode
