### ISSUE TITLE
Failure to create account

### ISSUE THREAD

**Issue by AlexandreFeren** [birdspotter-project/COS397#77]
error thrown after attempted account creation
Error: SMTP AUTH extension not supported by server 

information entered:
  username: aferen1
  password: IQoKkWNE8&bK^BW6FYY@
  email: alexandre.feren@maine.edu

**Comment by AlexandreFeren** [comment]
just a quick note: it still does show up under group requests, so I'm not sure exactly what is going on with it

**Comment by NickKania** [comment]
This is not a account issue, it is an issue with the email configuration.
