### ISSUE TITLE
Data view doesn't fail gracefully when not logged in

### ISSUE THREAD

**Issue by AlexandreFeren** [birdspotter-project/COS397#78]
data view option is available for public users, but because they do not have access to some of the data that is displayed in the data view, there is a key error. 

Suggested Solution: remove data view option for public user, or redirect public users to the home page after an attempt to access the data view.

**Comment by NickKania** [comment]
This can be done with a simple `login_required` decorator on the view see [accounts.views](https://github.com/birdspotter-project/COS397/blob/master/birdspotter/birdspotter/accounts/views.py)
