### ISSUE TITLE
Group requests should disappear on click

### ISSUE THREAD

**Issue by AlexandreFeren** [birdspotter-project/COS397#79]
clicking on approve/deny user does not give any feedback. I clicked twice on accept for a test user, and got 2 confirmation overlays, which is likely unintended behavior and I suspect may lead to undesired side effects.

**Comment by NickKania** [comment]
This is due to the page not refreshing. IIRC this is fixed in more recent branches.

**Comment by NickKania** [comment]
This is indeed fixed, the branch you are using must be out of date
